<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7C88RL8" ignored="0" name="Default test" tests="5" failures="1" timestamp="2020-05-11T12:18:55 BST" time="57.493" errors="0">
  <testcase name="loginTest" time="0.063" classname="com.core.ddf.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="37.389" classname="com.core.ddf.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Username and password does not match. Try again.">
      <![CDATA[java.lang.AssertionError: Username and password does not match. Try again.
at org.testng.Assert.fail(Assert.java:97)
at com.core.ddf.base.BaseTest.reportFailure(BaseTest.java:253)
at com.core.ddf.base.BaseTest.doLogin(BaseTest.java:128)
at com.core.ddf.testcases.LoginTest.loginTest(LoginTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.047" classname="com.core.ddf.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="15.998" classname="com.core.ddf.testcases.LoginTest"/>
  <testcase name="loginTest" time="0.039" classname="com.core.ddf.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
